name: SilKonfig
version: 1.1.beta
main: stephirio.silkonfig.Main
api-version: 1.16
authors: [ Stephirio ]
description: A simple plugin to customize dropped items when breaking blocks using a pickaxe with silk touch.
commands:
  silkonfig:
    description: Some commands related to the plugin.
