name: SilKonfig
version: ${project.version}
main: stephirio.silkonfig.Main
api-version: 1.16
softdepend: [ Vault, PlaceholderAPI ]
authors: [ Stephirio ]
description: A simple plugin to customize dropped items when breaking blocks using a pickaxe with silk touch.
